### ISSUE TITLE
Fails to import "matrix" from scipy v1.12.0

### ISSUE THREAD

**Issue by Firefly78** [novonordisk-research/ProcessOptimizer#235]
Fails to import `matrix` from the scipy package, with scipy 1.12.0.

It works with scipy 1.11.4.

Suggest importing matrix directly from numpy instead.

Stack trace:
```
    from ProcessOptimizer import Optimizer, expected_minimum
  File "C:\Repos\SiLA Library\Camera-IDS-U3-3080\.venv\lib\site-packages\ProcessOptimizer\__init__.py", line 21, in <module>
    from . import optimizer
  File "C:\Repos\SiLA Library\Camera-IDS-U3-3080\.venv\lib\site-packages\ProcessOptimizer\optimizer\__init__.py", line 1, in <module>
    from .base import base_minimize
  File "C:\Repos\SiLA Library\Camera-IDS-U3-3080\.venv\lib\site-packages\ProcessOptimizer\optimizer\base.py", line 17, in <module>
    from .optimizer import Optimizer
  File "C:\Repos\SiLA Library\Camera-IDS-U3-3080\.venv\lib\site-packages\ProcessOptimizer\optimizer\optimizer.py", line 22, in <module>
    from ..space.constraints import Constraints, SumEquals
  File "C:\Repos\SiLA Library\Camera-IDS-U3-3080\.venv\lib\site-packages\ProcessOptimizer\space\constraints.py", line 4, in <module>
    from scipy import matrix, linalg
ImportError: cannot import name 'matrix' from 'scipy' (C:\Repos\SiLA Library\Camera-IDS-U3-3080\.venv\lib\site-packages\scipy\__init__.py)
```

**Comment by sqbl** [comment]
Thank you very much for raising this. We have a PR on it's way to fix this. Stay tuned :-)

**Comment by CatSci** [comment]
Hi, is this issue fixed because I am still getting this issue?

**Comment by sqbl** [comment]
> Hi, is this issue fixed because I am still getting this issue?

Hi CatSci, 
Welcome to ProcessOptimizer. The fix has been implemented in the code, but we have not published a new version to pypi, yet. We expect to do so early next week. Until then, a (hopefully) functional version can be build from source, or a transient downgrade of scipy to e.g. 1.11.4 could solve the issue.

**Comment by sqbl** [comment]
> Hi, is this issue fixed because I am still getting this issue?

Dear CatSci,
The new version should be on pypi ("pip install ...") now. Hopefully, it has solved the issue. If not, feel free to reach out, and we will do our best to look into it ASAP.
